"""SEO metadata validation thresholds."""

IDEAL_TITLE_MIN = 50
IDEAL_TITLE_MAX = 60
TITLE_WARNING_MIN = 30
TITLE_WARNING_MAX = 65

IDEAL_DESC_MIN = 140
IDEAL_DESC_MAX = 160
DESC_WARNING_MIN = 70
DESC_WARNING_MAX = 165
